package ru.ts.toykernel.drawcomp;

import ru.ts.toykernel.geom.IBaseGisObject;
import ru.ts.toykernel.converters.ILinearConverter;
import ru.ts.gisutils.algs.common.MRect;

import java.awt.*;

/**
 * Этот интерфейс фактически определяет то как будет рисоваться объект
 * Painter for painting gis object, generated by IDrawObjRule
 */
public interface IPainter
{

    /**
     * Paint of gis object
     * @param g - graphics
	 * @param drawMe
	 * @param converter - converter for drawing
	 * @param drawSize -size of draw field in pixels @return counts of painted points,lines,polygons
	 * @throws Exception - throw when error painting
	 */
    int[] paint(Graphics g, IBaseGisObject drawMe, ILinearConverter converter, Point drawSize) throws Exception;

	//Shape createShape();

	MRect getRect(Graphics graphics, IBaseGisObject obj, ILinearConverter converter) throws Exception;

	MRect getDrawRect(Graphics graphics,IBaseGisObject obj, ILinearConverter converter)throws Exception;

	Shape createShape(IBaseGisObject drawMe, ILinearConverter converter)throws Exception;
}
